#!/bin/bash

#have to be finished

sudo fdisk -l | sed -e 's/\([a-z0-9/]*\).*/\1/' -n -e 's/^\/dev.*/&/p' | tail -n1 ~                                                                                  
